### ISSUE TITLE
Enhancement: Upgrade Sphinx version to eliminate incorrect syntax errors

### ISSUE THREAD

**Issue by pushfoo** [pyglet/pyglet#947]
Older Sphinx versions, including pyglet's, do not report correct locations for syntax errors. Upgrading to 6.2.1 or later should fix some of the worst of these (see https://github.com/sphinx-doc/sphinx/issues/11026).

### Why this is relevant

1. It's annoying when working on doc
2. It has been discussed without objections before [on Discord](https://discord.com/channels/438622377094414346/1143036529523040276/1143375701265887242)
3. It delays PRs when people unfamiliar with the problem run into it (see this [example from arcade](https://github.com/pythonarcade/arcade/pull/1690#pullrequestreview-1410051497))

For an example of how this affects our current code:

```console
/home/pushfoo/src/pyglet/pyglet/graphics/shader.py:docstring of pyglet.graphics.shader.Attribute:1: WARNING: Definition list ends without a blank line; unexpected unindent.
```
However, there is no definition list at line 1 of Attribute's docstring:

https://github.com/pyglet/pyglet/blob/66466f80cb9b2437971851bbaf0a997faf7343bb/pyglet/graphics/shader.py#L151-L153

### Tasks required

To my understanding per [prior discussion on Discord](https://discord.com/channels/438622377094414346/1143036529523040276/1143375701265887242):
* We're still on an old version because of our readthedocs config
* Benjamin has no objections to upgrading as long as build keeps working

This implies we have to update the following:

- [ ] Our sphinx version
     * Important note: Sphinx 7.2.0+ requires Python 3.9+, which can create an ugly situation for listing project requirements + readthedocs
- [ ] Any incompatible plugins
- [ ] Our readthedocs config
- [ ] Any build scripts which need version bumps (I can't find any yet)

**Comment by pushfoo** [comment]
Another benefit of using Sphinx 7.1+ is that [we can show the full copyright list from LICENSE](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-copyright):

> *Changed in version 7.1*: The value may now be a sequence of copyright statements in the above form, which will be displayed each to their own line.

**Comment by pushfoo** [comment]
Closing per Discord discussion and db94ffd
